"""
Frame diffusion: turn a beat still into genuinely moving footage using only
an image-to-image model.

Why this exists
---------------
OpenRouter currently exposes ZERO models with `video` among their
`output_modalities` (verified directly against /api/v1/models), so no amount
of OpenRouter credit can buy an image-to-video model here. Every other route
to motion either costs money the agency does not have (Pollinations bills
video in pollen) or depends on a free GPU tier that saturates (HF ZeroGPU
Spaces - which is exactly why issue #6 shipped dead characters).

What frame diffusion does instead
---------------------------------
An autoregressive image chain. Frame 0 is the validated beat still. Frame i+1
is generated by the same image model conditioned on TWO references:

  1. the ORIGINAL beat still  -> the identity anchor
  2. the previous frame       -> where the motion currently is

plus a motion prompt asking for the action "a fraction further along".
ffmpeg's optical-flow `minterpolate` then fills the gaps up to a 24 fps
delivery frame rate.

Re-anchoring every frame to the original is the whole trick. A naive chain
(previous frame only) compounds its own error, and the character morphs into
a different person within a few frames - which reads as horrifying rather
than animated. Re-anchoring pulls the face back toward the real face on
every step, so drift stays bounded no matter how long the chain runs.

Cost: gemini-2.5-flash-image is ~$0.00003 per image, so an ~11s reel at an
8 fps generation rate is ~90 frames, roughly $0.003. Generation deliberately
runs slower than delivery: generating 24 independent frames per second buys
per-frame noise and shimmer, not extra motion, while tripling the bill.
"""

import base64
import json
import os
import subprocess
import time

import requests

from src.openrouter_media import (
    OPENROUTER_BASE,
    MediaGenerationError,
    _api_key,
    _openrouter_post,
)
import src.billing as billing

FFMPEG_BIN = os.environ.get("FFMPEG_BIN", "ffmpeg")

# Delivery frame rate. The final MP4 is 24 fps regardless of how many frames
# were actually generated.
OUTPUT_FPS = 24

# Generation rate. 8 fps of deliberate motion, interpolated up to 24.
DEFAULT_SOURCE_FPS = 8

# Per-frame sanity bounds, on a 0-255 mean absolute luma difference between the
# 64x112 grayscale signature of two frames.
#
# The stall bound is deliberately near zero. Consecutive generated frames are
# meant to be only a fraction apart, so their delta is naturally tiny and
# almost always above this; a lower bound would "nudge" nearly every frame and
# silently double the API bill. A true duplicate lands at exactly 0.
STALL_DELTA = 0.05

# Cumulative drift from the anchor warns about the opposite failure: the chain
# walking away from the original subject until it morphs into something else.
MAX_DRIFT = 34.0

# Reference images are downscaled before being base64'd. Sending full-res
# 9:16 stills on every one of ~90 requests is pure wasted bandwidth and
# noticeably slower encodes.
REFERENCE_MAX_SIDE = 768

# Ordered ladder, cheapest-and-best first. All three accept image+text input,
# which is the only hard requirement for a re-anchored chain. All three are
# PAID - OpenRouter publishes no free image-output model at all - so under the
# default free-only billing policy every rung is dropped and this provider
# reports itself unavailable rather than spending.
FRAME_LADDER = {
    "gemini_flash": "google/gemini-2.5-flash-image",
    "gpt5_mini": "openai/gpt-5-image-mini",
    "gemini_31": "google/gemini-3.1-flash-image",
}
DEFAULT_FRAME_ORDER = "gemini_flash,gpt5_mini,gemini_31"

# Interpolation rungs, richest first. `{fps}` is substituted.
#
#   mci     - motion-compensated interpolation, real optical flow. Best result,
#             but the aobmc/bidir combination is not reliable across ffmpeg
#             builds (it fails at EOF on ffmpeg 6.x).
#   mci_obb - same motion compensation with the simpler, older OBMC mode.
#   blend   - blends neighbouring frames; no motion estimation, so it cannot
#             fail on "invalid data" and is a safe smooth-looking result.
#   fps     - frame duplication. Always works; last resort so a paid chain is
#             never thrown away over a filter setting.
INTERPOLATION_LADDER = [
    ("mci", "minterpolate=fps={fps}:mi_mode=mci:mc_mode=aobmc:me_mode=bidir:vsbmc=1"),
    ("mci_obb", "minterpolate=fps={fps}:mi_mode=mci:mc_mode=obmc:me_mode=bidir"),
    ("blend", "minterpolate=fps={fps}:mi_mode=blend"),
    ("fps", "fps={fps}"),
]

STYLE_LOCK = (
    "identical framing, identical camera position, identical lighting, "
    "identical wardrobe, identical background, photorealistic, handheld "
    "smartphone video"
)

# Appended on the second attempt when the first chain animated too gently to
# clear the motion gate. Per-frame deltas from a re-anchored image chain are
# inherently gentler than a native video model's output, so the honest fix is
# to ask for a larger physical change - never to lower the gate, because the
# dead-character camera pan sits just underneath it.
MOTION_AMPLIFY = (
    "AMPLIFY the movement: a clearly visible change of pose between each "
    "frame, an obvious head turn and a visible shift of body weight, not a "
    "near-identical frame"
)


class FrameDiffusionError(RuntimeError):
    """No model could produce a coherent frame chain."""


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------
def _run(cmd: list, timeout: int = 300) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, timeout=timeout, text=True)


def _shrink_reference(src: str, dst: str) -> str:
    """Downscale a still for use as an in-prompt reference."""
    try:
        from PIL import Image
    except ImportError:
        return src

    try:
        with Image.open(src) as im:
            im = im.convert("RGB")
            w, h = im.size
            scale = REFERENCE_MAX_SIDE / max(w, h)
            if scale >= 1.0:
                im.save(dst, "JPEG", quality=88)
                return dst
            im.resize((max(1, int(w * scale)), max(1, int(h * scale))), Image.LANCZOS).save(
                dst, "JPEG", quality=88
            )
        return dst
    except Exception:
        return src


def _data_url(path: str) -> str:
    with open(path, "rb") as fh:
        encoded = base64.b64encode(fh.read()).decode("ascii")
    ext = os.path.splitext(path)[1].lstrip(".").lower() or "jpeg"
    if ext == "jpg":
        ext = "jpeg"
    return f"data:image/{ext};base64,{encoded}"


def _luma_signature(path: str):
    """Small grayscale fingerprint used for the drift/delta gates."""
    try:
        import numpy as np
        from PIL import Image
    except ImportError:
        return None
    try:
        with Image.open(path) as im:
            arr = np.asarray(im.convert("L").resize((64, 112), Image.LANCZOS)).astype(float)
        return arr
    except Exception:
        return None


def _mean_abs(a, b) -> float:
    if a is None or b is None:
        return -1.0
    import numpy as np

    return float(np.abs(a - b).mean())


def _frame_is_usable(path: str) -> tuple[bool, str]:
    """Cheaper and looser than validate_image: frames are re-cropped by
    ffmpeg anyway, so aspect ratio is not this gate's business."""
    if not os.path.exists(path):
        return False, "frame missing"
    size = os.path.getsize(path)
    if size < 15_000:
        return False, f"frame too small ({size} bytes)"
    try:
        from PIL import Image, ImageStat
    except ImportError:
        return True, "ok (Pillow unavailable)"
    try:
        with Image.open(path) as im:
            im.load()
            w, h = im.size
            if w < 256 or h < 256:
                return False, f"frame too low-res ({w}x{h})"
            stddev = ImageStat.Stat(im.convert("L")).stddev[0]
            if stddev < 10.0:
                return False, f"frame is flat (luma stddev {stddev:.1f})"
    except Exception as exc:
        return False, f"unreadable frame: {exc}"
    return True, "ok"


# --------------------------------------------------------------------------
# one frame
# --------------------------------------------------------------------------
def _extract_images_endpoint(body: dict) -> list[bytes]:
    blobs = []
    for entry in body.get("data") or []:
        if entry.get("b64_json"):
            blobs.append(base64.b64decode(entry["b64_json"]))
        elif entry.get("url"):
            blobs.append(requests.get(entry["url"], timeout=90).content)
    return blobs


def _extract_chat_endpoint(body: dict) -> list[bytes]:
    blobs = []
    for choice in body.get("choices") or []:
        message = choice.get("message") or {}
        for image in message.get("images") or []:
            url = (image.get("image_url") or {}).get("url")
            if not url:
                continue
            if url.startswith("data:"):
                blobs.append(base64.b64decode(url.split(",", 1)[1]))
            else:
                blobs.append(requests.get(url, timeout=90).content)
    return blobs


def _request_frame(
    model: str,
    prompt: str,
    reference_paths: list[str],
    seed: int,
) -> list[bytes]:
    """Generate one frame, trying the image endpoint then chat completions.

    The two endpoints disagree about how they accept a reference image, and
    which one supports it varies by model. Rather than assume, try both and
    keep whichever returns an actual image.
    """
    refs = [_data_url(p) for p in reference_paths if os.path.exists(p)]
    errors: list[str] = []

    # 1. Dedicated image endpoint.
    if refs:
        payload = {
            "model": model,
            "prompt": prompt,
            "aspect_ratio": "9:16",
            "seed": seed,
            "n": 1,
            "input_references": [{"type": "image_url", "image_url": {"url": r}} for r in refs],
        }
    else:
        payload = {"model": model, "prompt": prompt, "aspect_ratio": "9:16", "seed": seed, "n": 1}

    try:
        resp = _openrouter_post("/images", payload, raw=False, attempts=2)
        blobs = _extract_images_endpoint(resp.json())
        if blobs and len(blobs[0]) > 15_000:
            return blobs[0]
        errors.append("/images returned no usable image")
    except MediaGenerationError as exc:
        errors.append(f"/images: {str(exc)[:140]}")

    # 2. Chat completions multimodal path.
    content: list[dict] = [{"type": "text", "text": prompt}]
    for ref in refs:
        content.append({"type": "image_url", "image_url": {"url": ref}})

    chat_payload = {
        "model": model,
        "messages": [{"role": "user", "content": content}],
        "modalities": ["image", "text"],
    }
    try:
        resp = _openrouter_post("/chat/completions", chat_payload, raw=False, attempts=2)
        body = resp.json()
        blobs = _extract_chat_endpoint(body)
        if blobs and len(blobs[0]) > 15_000:
            return blobs[0]
        errors.append("/chat/completions returned no usable image")
    except MediaGenerationError as exc:
        errors.append(f"/chat/completions: {str(exc)[:140]}")
    except Exception as exc:
        errors.append(f"/chat/completions: {type(exc).__name__}: {str(exc)[:120]}")

    raise MediaGenerationError(f"{model} could not produce a frame: " + " | ".join(errors))


def _motion_prompt(motion_prompt: str, index: int, total: int, amplify: bool = False) -> str:
    """Describe the action as a progression so each step is a small delta."""
    progress = f"({index + 1} of {total} in a continuous shot)"
    if index == 0:
        beat = f"BEGIN the movement: {motion_prompt}"
    elif index >= total - 1:
        beat = f"HOLD and settle at the end of the movement: {motion_prompt}"
    else:
        beat = f"CONTINUE the same movement a fraction further along: {motion_prompt}"
    extra = f" {MOTION_AMPLIFY}" if amplify else ""
    return f"{beat} {progress}{extra}. {STYLE_LOCK}. Do not redraw or restyle the subject."


def _generate_chain(
    still_path: str,
    motion_prompt: str,
    frames_dir: str,
    frame_count: int,
    base_seed: int,
    log,
    amplify: bool = False,
) -> list[str]:
    """Walk the chain and return the ordered list of frame paths."""
    os.makedirs(frames_dir, exist_ok=True)

    anchor_small = os.path.join(frames_dir, "_anchor.jpg")
    _shrink_reference(still_path, anchor_small)

    prev_small = anchor_small
    prev_sig = _luma_signature(still_path)
    anchor_sig = _luma_signature(anchor_small)
    if anchor_sig is None:
        anchor_sig = prev_sig

    order = [
        k.strip()
        for k in os.environ.get("FRAME_PROVIDER_ORDER", DEFAULT_FRAME_ORDER).split(",")
        if k.strip()
    ]
    models = [(k, m) for k, m in billing.filter_ladder(order, FRAME_LADDER, "frame diffusion")]
    if not models:
        # Do not start generating: under the free-only policy this is the
        # expected path, and the caller needs a clear reason to fall back
        # rather than a wall of per-frame billing errors.
        raise FrameDiffusionError(
            "no free image model is permitted, so frame diffusion cannot run "
            "(every FRAME_LADDER entry is a paid OpenRouter model). Characters "
            "will fall back to the free rungs."
        )

    paths: list[str] = []
    # A model that fails on frame 3 should not doom frames 4..N. Remember which
    # rungs proved they work and prefer them for the rest of the chain.
    preferred = models[0][1]
    drift_warnings = 0

    for i in range(frame_count):
        out_path = os.path.join(frames_dir, f"f{i:04d}.jpg")
        prompt = _motion_prompt(motion_prompt, i, frame_count, amplify)

        blob = None
        last_error = None
        for key, model in models:
            if model != preferred:
                continue
            try:
                blob = _request_frame(model, prompt, [anchor_small, prev_small], base_seed + i)
                break
            except MediaGenerationError as exc:
                last_error = exc
        if blob is None:
            # Preferred rung failed; let any rung try, and adopt whichever works.
            for key, model in models:
                if model == preferred:
                    continue
                try:
                    blob = _request_frame(model, prompt, [anchor_small, prev_small], base_seed + i)
                    preferred = model
                    last_error = None
                    log(f"  [fd] frame {i}: fell back to {model}")
                    break
                except MediaGenerationError as exc:
                    last_error = exc
        if blob is None:
            raise FrameDiffusionError(
                f"frame {i + 1}/{frame_count} could not be generated: {last_error}"
            )

        with open(out_path, "wb") as fh:
            fh.write(blob)

        ok, reason = _frame_is_usable(out_path)
        if not ok:
            os.remove(out_path)
            raise FrameDiffusionError(f"frame {i + 1}/{frame_count} unusable: {reason}")

        sig = _luma_signature(out_path)
        delta = _mean_abs(sig, prev_sig)
        drift = _mean_abs(sig, anchor_sig)

        if 0 <= delta < STALL_DELTA:
            # The model returned a byte-for-byte-equivalent picture. Nudge it
            # once with a fresh seed; a genuinely frozen chain is a slideshow.
            log(f"  [fd] frame {i}: stalled (delta {delta:.2f}) - nudging seed")
            try:
                retry = _request_frame(preferred, prompt, [anchor_small, prev_small], base_seed + i + 5000)
                with open(out_path, "wb") as fh:
                    fh.write(retry)
                sig = _luma_signature(out_path)
                delta = _mean_abs(sig, prev_sig)
                drift = _mean_abs(sig, anchor_sig)
            except MediaGenerationError:
                pass

        prev_small_new = os.path.join(frames_dir, f"_prev{i:04d}.jpg")
        _shrink_reference(out_path, prev_small_new)
        prev_small = prev_small_new
        prev_sig = sig
        paths.append(out_path)

        if i % 6 == 0 or i == frame_count - 1:
            log(f"  [fd] frame {i + 1}/{frame_count} (delta {delta:.1f}, drift {drift:.1f})")
        if drift > MAX_DRIFT:
            drift_warnings += 1

    if drift_warnings > frame_count * 0.4:
        log(
            f"  [fd] WARNING: {drift_warnings}/{frame_count} frames drifted far from the anchor - "
            f"the subject may be morphing between frames"
        )

    return paths


# --------------------------------------------------------------------------
# public entry point
# --------------------------------------------------------------------------
def animate_still_to_clip(
    img_path: str,
    motion_prompt: str,
    out_path: str,
    duration: float,
    seed: int = 0,
    log=print,
) -> str:
    """Animate one beat still into a moving MP4. Returns out_path.

    Raises FrameDiffusionError rather than writing a dead clip, so the caller
    can fall through to the next provider rather than shipping a slideshow.
    """
    src_fps = int(os.environ.get("FRAME_SOURCE_FPS", DEFAULT_SOURCE_FPS))
    src_fps = max(2, min(src_fps, 12))
    # +2 frames of headroom. Optical-flow interpolation synthesises frames
    # *between* existing ones and cannot extrapolate past the last, so N input
    # frames only ever yield N-1 intervals - a 3.0s beat rendered from exactly
    # 24 frames came back at 2.79s. The renderer computes its crossfade
    # offsets from the exact beat duration, so a short clip stalls the stitch.
    frame_count = max(4, int(round(duration * src_fps)) + 2)

    # Cost is per generated frame, so it is knowable before spending anything.
    # ~$0.00003/frame on gemini-2.5-flash-image puts a full 3-beat ~11s reel
    # near $0.003, or ~$0.006 if a beat needs the amplified retry. Under the
    # default free-only policy none of this is spent: the ladder check below
    # refuses every rung first.
    if not billing.filter_ladder(
        [n.strip() for n in os.environ.get("FRAME_PROVIDER_ORDER", DEFAULT_FRAME_ORDER).split(",") if n.strip()],
        FRAME_LADDER,
        "frame diffusion",
    ):
        raise FrameDiffusionError(
            "frame diffusion is disabled by the free-only billing policy "
            "(all of its models are paid); no credit was spent"
        )

    est = frame_count * 0.00003 * int(os.environ.get("FRAME_ATTEMPTS", "2"))
    log(f"  [fd] budget: ~{frame_count} frames x up to {os.environ.get('FRAME_ATTEMPTS', '2')} "
        f"attempts = ~${est:.4f} for this beat")

    workdir = out_path + ".frames"
    os.makedirs(workdir, exist_ok=True)

    try:
        # Two attempts. A re-anchored image chain sometimes animates too
        # gently to clear the motion gate, and the correct response is to ask
        # for a bigger physical change - not to relax the gate, which would
        # let the motionless camera-pan fallback pass as live motion.
        attempts = int(os.environ.get("FRAME_ATTEMPTS", "2"))
        best: tuple[float, str] | None = None

        for attempt in range(1, attempts + 1):
            amplify = attempt > 1
            if amplify:
                log(f"  [fd] first chain animated too gently - retrying with amplified motion")

            for name in os.listdir(workdir):
                try:
                    os.remove(os.path.join(workdir, name))
                except OSError:
                    pass

            _generate_chain(img_path, motion_prompt, workdir, frame_count, seed + attempt * 7919, log, amplify)

            # Optical-flow interpolation is what turns 8 deliberate frames per
            # second into something that reads as smooth video rather than a
            # flipbook. It also hides the small inconsistencies between
            # independently generated frames.
            # Interpolation filter ladder.
            #
            # The first rung (motion-compensated bidirectional optical flow) is
            # the best-looking but the least portable. On CI's ffmpeg 6.1.1 it
            # died with "Invalid data found when processing input" / "Error
            # marking filters as finished" at EOF - a known minterpolate
            # failure mode with aobmc + bidir. That single filter failure threw
            # away ~100 correctly generated frames per reel, i.e. the frames
            # we had already paid for.
            #
            # So each rung is a progressively more conservative interpolation,
            # and the first that produces a playable file wins. Plain `fps`
            # cannot fail on motion data at all, which guarantees the chain is
            # never wasted.
            for filter_label, interp in INTERPOLATION_LADDER:
                vf = (
                    f"{interp.format(fps=OUTPUT_FPS)},"
                    f"scale=720:1280:force_original_aspect_ratio=increase,crop=720:1280,"
                    f"setsar=1,format=yuv420p"
                )
                proc = _run([
                    FFMPEG_BIN, "-y", "-v", "error",
                    "-framerate", str(src_fps),
                    "-i", os.path.join(workdir, "f%04d.jpg"),
                    "-t", str(duration),
                    "-vf", vf,
                    "-an", "-c:v", "libx264", "-preset", "fast", "-crf", "20",
                    out_path,
                ], timeout=900)

                if proc.returncode == 0 and os.path.exists(out_path) and os.path.getsize(out_path) > 10_000:
                    if filter_label != "mci":
                        log(f"  [fd] interpolation fell back to '{filter_label}' "
                            f"(richer optical-flow modes are unavailable on this ffmpeg)")
                    break

                tail = (proc.stderr or "").strip().splitlines()
                log(f"  [fd] interpolation '{filter_label}' failed: {tail[-1][:150] if tail else 'unknown'}")
            else:
                raise FrameDiffusionError(
                    f"every interpolation mode failed; last error: {tail[-1][:200] if tail else 'unknown'}"
                )

            size = os.path.getsize(out_path)
            if size < 10_000:
                raise FrameDiffusionError(f"interpolated clip is truncated ({size} bytes)")

            # Measure our own output. Reusing the shared gate here means the
            # provider and the renderer can never disagree about whether the
            # character actually moved.
            from src.motion import measure_motion, MOTION_THRESHOLD

            motion = measure_motion(out_path)
            log(
                f"  [fd] attempt {attempt}: {frame_count} frames, motion {motion:.2f} "
                f"(live >= {MOTION_THRESHOLD})"
            )

            if best is None or motion > best[0]:
                best = (motion, out_path + ".best.mp4")
                try:
                    if os.path.exists(best[1]):
                        os.remove(best[1])
                    import shutil

                    shutil.copy(out_path, best[1])
                except OSError:
                    best = (motion, out_path)

            if motion >= MOTION_THRESHOLD:
                break

        if best is None:
            raise FrameDiffusionError("no frames were generated")

        motion, source = best
        from src.motion import MOTION_THRESHOLD, validate_clip

        if motion < MOTION_THRESHOLD:
            ok, reason = validate_clip(source if source != out_path else out_path)
            raise FrameDiffusionError(
                f"animated too gently: best motion {motion:.2f} < {MOTION_THRESHOLD} ({reason})"
            )

        if source != out_path:
            import shutil

            shutil.copy(source, out_path)
            try:
                os.remove(source)
            except OSError:
                pass

        log(f"  [fd] wrote {out_path} ({os.path.getsize(out_path) // 1024} KB, motion {motion:.2f})")
        return out_path

    finally:
        for name in os.listdir(workdir) if os.path.isdir(workdir) else []:
            try:
                os.remove(os.path.join(workdir, name))
            except OSError:
                pass
        try:
            os.rmdir(workdir)
        except OSError:
            pass


def model_label() -> str:
    order = os.environ.get("FRAME_PROVIDER_ORDER", DEFAULT_FRAME_ORDER)
    key = order.split(",")[0].strip()
    return FRAME_LADDER.get(key, key)
